import type { AMR } from './types';

export function createInitialRobots(): AMR[] {
  return [
    {
      id: 'AMR-01',
      name: 'AMR-01',
      color: '#00d4ff',
      position: { x: 1, y: 0 },
      destination: { x: 22, y: 0 },
      destinationLabel: 'Drop D',
      route: { waypoints: [], currentIndex: 0, blocked: false },
      task: 'TASK-101',
      taskId: 'TASK-101',
      battery: 82,
      speed: 1.2,
      status: 'MOVING',
      priority: 'HIGH',
      intent: 'PROCEEDING TO DESTINATION',
      decision: 'PROCEED',
      confidence: 94,
      decisionReason: ['No collision predicted', 'Route reservation available', 'High task priority'],
      waitingTime: 0,
      distanceTravelled: 0,
      online: true,
    },
    {
      id: 'AMR-02',
      name: 'AMR-02',
      color: '#22d3aa',
      position: { x: 1, y: 7 },
      destination: { x: 22, y: 7 },
      destinationLabel: 'Drop E',
      route: { waypoints: [], currentIndex: 0, blocked: false },
      task: 'TASK-102',
      taskId: 'TASK-102',
      battery: 76,
      speed: 1.0,
      status: 'MOVING',
      priority: 'NORMAL',
      intent: 'PROCEEDING TO DESTINATION',
      decision: 'PROCEED',
      confidence: 91,
      decisionReason: ['No collision predicted', 'Normal task priority', 'Clear path ahead'],
      waitingTime: 0,
      distanceTravelled: 0,
      online: true,
    },
    {
      id: 'AMR-03',
      name: 'AMR-03',
      color: '#fbbf24',
      position: { x: 1, y: 14 },
      destination: { x: 22, y: 14 },
      destinationLabel: 'Drop F',
      route: { waypoints: [], currentIndex: 0, blocked: false },
      task: 'TASK-103',
      taskId: 'TASK-103',
      battery: 68,
      speed: 0.9,
      status: 'MOVING',
      priority: 'HIGH',
      intent: 'PROCEEDING TO DESTINATION',
      decision: 'PROCEED',
      confidence: 89,
      decisionReason: ['No collision predicted', 'High task priority', 'Route is clear'],
      waitingTime: 0,
      distanceTravelled: 0,
      online: true,
    },
    {
      id: 'AMR-04',
      name: 'AMR-04',
      color: '#f472b6',
      position: { x: 11, y: 15 },
      destination: { x: 22, y: 14 },
      destinationLabel: 'Drop F',
      route: { waypoints: [], currentIndex: 0, blocked: false },
      task: null,
      taskId: null,
      battery: 90,
      speed: 1.1,
      status: 'COMPLETED',
      priority: 'NORMAL',
      intent: 'IDLE',
      decision: 'IDLE',
      confidence: 100,
      decisionReason: ['No active task', 'Standing by for assignment'],
      waitingTime: 0,
      distanceTravelled: 0,
      online: true,
    },
    {
      id: 'AMR-05',
      name: 'AMR-05',
      color: '#a78bfa',
      position: { x: 5, y: 15 },
      destination: { x: 11, y: 15 },
      destinationLabel: 'Charging Station',
      route: { waypoints: [], currentIndex: 0, blocked: false },
      task: null,
      taskId: null,
      battery: 45,
      speed: 0.8,
      status: 'CHARGING',
      priority: 'LOW',
      intent: 'HEADING TO CHARGING STATION',
      decision: 'PROCEED',
      confidence: 95,
      decisionReason: ['Low battery detected', 'Routing to charging station'],
      waitingTime: 0,
      distanceTravelled: 0,
      online: true,
    },
  ];
}
